/*Alter Queries for Student Table*/

ALTER TABLE L_STUDENT
ADD FOREIGN KEY (DEPTID)
REFERENCES L_DEPARTMENT(DEPTID);

/*Alter Queries for STAFF Table*/

ALTER TABLE L_STAFF
ADD FOREIGN KEY (DEPTID)
REFERENCES L_DEPARTMENT(DEPTID);

/*Alter Queries for BOOK Table*/

ALTER TABLE L_BOOK
ADD FOREIGN KEY (DEPTID)
REFERENCES L_DEPARTMENT(DEPTID);

ALTER TABLE L_BOOK
ADD FOREIGN KEY (AUTHOR_ID)
REFERENCES L_AUTHOR(AUTHOR_ID);

ALTER TABLE L_BOOK
ADD FOREIGN KEY (PUBLISHER_ID)
REFERENCES L_PUBLISHER(PUBLISHER_ID);

/*Alter Queries for ISSUEDETAILS Table*/

ALTER TABLE L_ISSUEDETAILS
ADD FOREIGN KEY (STUDENTID)
REFERENCES L_STUDENT(STUDENTID);

ALTER TABLE L_ISSUEDETAILS
ADD FOREIGN KEY (DEPTID)
REFERENCES L_DEPARTMENT(DEPTID);

ALTER TABLE L_ISSUEDETAILS
ADD FOREIGN KEY (STAFFID)
REFERENCES L_STAFF(STAFFID);

ALTER TABLE L_BOOK
ADD ISSUENUM VARCHAR(30);

ALTER TABLE L_BOOK
ADD FOREIGN KEY (ISSUENUM)
REFERENCES L_ISSUEDETAILS(ISSUENUM);



ALTER TABLE L_STUDENT
ADD STAFFID VARCHAR2(10);