select * from jpatel2810.l_student;
select * from JPATEL2810.l_staff;
select * from L_BOOK;
select * from JPATEL2810.l_issuedetails;
select * from JPATEL2810.l_department;

select * from L_BOOK;

SELECT * FROM L_STUDENT;

grant all
on L_STUDENT
to jpatel2810;

grant all
on L_AUTHOR
to jpatel2810;

grant all
on L_BOOK
to jpatel2810;

grant all
on L_DEPARTMENT
to jpatel2810;

grant all
on L_ISSUEDETAILS
to jpatel2810;

grant all
on L_STAFF
to jpatel2810;

grant all
on L_PUBLISHER
to jpatel2810;


/*Student Table Created*/

CREATE TABLE L_STUDENT
(STUDENTID VARCHAR(10) CONSTRAINT L_STUDENT_STUDENTID_PK PRIMARY KEY,
FNAME VARCHAR(20) CONSTRAINT L_STUDENT_FNAME_NN NOT NULL,
LNAME VARCHAR(20) CONSTRAINT L_STUDENT_LNAME_NN NOT NULL,
BIRTHDATE DATE ,
ADDRESS VARCHAR(200) CONSTRAINT L_STUDENT_STATE_UK UNIQUE,
EMAILID VARCHAR(30) CONSTRAINT L_STUDENT_EMAILID_UK UNIQUE,
MOBILENUM CHAR(15) CONSTRAINT L_STUDENT_MOBILENUM_NN NOT NULL,
DEPTID VARCHAR(10),
CURRENTYEAR VARCHAR(30) CONSTRAINT L_STUDENT_CURRENTYEAR_NN NOT NULL,
SECURITY_Q VARCHAR(30) CONSTRAINT L_STUDENT_SECURITY_Q_NN NOT NULL,
SECURITY_A VARCHAR(30) CONSTRAINT L_STUDENT_SECURITY_A_NN NOT NULL,
REGI_DATE DATE DEFAULT SYSDATE,
USER_TYPE CHAR(2) CONSTRAINT  L_STUDENT_USER_TYPE_CK CHECK(USER_TYPE IN('ST'))
);

select * from L_STUDENT;
/*Create Department Table*/

CREATE TABLE L_DEPARTMENT
(DEPTID VARCHAR(10) CONSTRAINT L_DEPARTMENT_DEPTID_PK PRIMARY KEY,
DEPTNAME VARCHAR(30) CONSTRAINT L_DEPARTMENT_DEPTNAME_NN NOT NULL,
STUDENTID VARCHAR(10),
STAFFID VARCHAR(10)
);

/*Create BOOK TABLE*/

CREATE TABLE L_BOOK
(BOOKNUM VARCHAR(10) CONSTRAINT L_BOOK_BOOKNUM_PK PRIMARY KEY,
BOOKTITLE VARCHAR(30) CONSTRAINT L_BOOK_BOOKTITLE_NN NOT NULL,
ISBNNUM VARCHAR(30) CONSTRAINT L_BOOK_ISBNNUMBER_UK UNIQUE,
AUTHOR_ID VARCHAR(10),
PUBLISHER_ID VARCHAR(10),
DEPTID VARCHAR(10),
COPIESLEFT CHAR(1) CONSTRAINT L_BOOK_COPIESLEFT_CK CHECK (COPIESLEFT IN ('Y','N'))
);

ALTER TABLE L_BOOK
ADD ISSUENUM VARCHAR(30);



/*Create Staff-Member Table*/
DROP TABLE  L_STAFF;
CREATE TABLE L_STAFF
(STAFFID VARCHAR(10) CONSTRAINT L_STAFF_STAFFID_PK PRIMARY KEY,
FNAME VARCHAR(20) CONSTRAINT L_STAFF_FNAME_NN NOT NULL,
LNAME VARCHAR(20) CONSTRAINT L_STAFF_LNAME_NN NOT NULL,
DEPTID VARCHAR(10),
BIRTHDATE DATE ,
ADDRESS VARCHAR(200) CONSTRAINT L_STAFF_STATE_UK UNIQUE,
EMAILID VARCHAR(30) CONSTRAINT L_STAFF_EMAILID_UK UNIQUE,
MOBILENUM CHAR(15) CONSTRAINT L_STAFF_MOBILENUM_NN NOT NULL,
SECURITY_Q VARCHAR(30) CONSTRAINT L_STAFF_SECURITY_Q_NN NOT NULL,
SECURITY_A VARCHAR(30) CONSTRAINT L_STAFF_SECURITY_A_NN NOT NULL,
REGI_DATE DATE DEFAULT SYSDATE,
USER_TYPE CHAR(2) CONSTRAINT  L_STAFF_USER_TYPE_CK CHECK(USER_TYPE IN('SM'))
);

/*Create Book Issue Details Table*/

CREATE TABLE L_ISSUEDETAILS
(ISSUENUM VARCHAR(30) CONSTRAINT L_ISSUEDETAILS_ISSUENAME_PK PRIMARY KEY,
ISSUE_DATE DATE CONSTRAINT L_ISSUEDETAILS_ISSUEDATE_NN NOT NULL,
BOOKNUM VARCHAR(10),
DUE_DATE DATE CONSTRAINT L_ISSUEDETAILS_DUEDATE_NN NOT NULL,
RETURN_DATE DATE CONSTRAINT L_ISSUEDETAILS_RETURN_DATE_NN NOT NULL,
STUDENTID VARCHAR(10),
STAFFID VARCHAR(10),
DEPTID VARCHAR(10) 
);

/*Create Publisher Details Table*/

CREATE TABLE L_PUBLISHER
(PUBLISHER_ID VARCHAR(10) CONSTRAINT L_PUBLISHER_PUBLISHER_ID_PK PRIMARY KEY,
 PUB_NAME VARCHAR(20) CONSTRAINT L_PUBLISHER_PUB_NAME_NN NOT NULL,
 PUB_YEAR VARCHAR(30) CONSTRAINT L_PUBLISHER_PUB_YEAR_NN NOT NULL,
 EDITION VARCHAR(10) CONSTRAINT L_PUBLISHER_EDITION_NN NOT NULL,
 ADDRESS VARCHAR(200) CONSTRAINT L_PUBLISHER_ADDRESS_NN NOT NULL,
 PHONE_NUM VARCHAR(13) CONSTRAINT L_PUBLISHER_PHONE_NUM_NN NOT NULL,
 EMAILID VARCHAR(30) CONSTRAINT L_PUBLISHER_EMAILID_UK UNIQUE
);

/*Create Author Details Table*/

CREATE TABLE L_AUTHOR 
(AUTHOR_ID VARCHAR(10) CONSTRAINT L_AUTHOR_AUTHOR_ID_PK PRIMARY KEY,
 AUTHOR_NAME VARCHAR(20) CONSTRAINT L_AUTHOR_AUTHOR_NAME_NN NOT NULL,
 ADDRESS VARCHAR(200) CONSTRAINT L_AUTHOR_STATE_UK UNIQUE,
 EMAILID VARCHAR(30) CONSTRAINT L_AUTHOR_EMAILID_UK UNIQUE,
 PHONE VARCHAR(13) CONSTRAINT L_AUTHOR_PHONE_NN NOT NULL
);

INSERT INTO L_AUTHOR(AUTHOR_ID,AUTHOR_NAME,ADDRESS,EMAILID,PHONE)
  VALUES('A101','Krystal','12-1260 ROOSERVELT NY-113352','krystal23@gmail.com',800-399-6716);






