/* Queries for Union*/

SELECT STUDENTID, deptid FROM L_STUDENT
UNION 
SELECT ISSUENUM, deptid FROM L_ISSUEDETAILS;

SELECT STUDENTID,FNAME ,deptid, birthdate FROM L_STUDENT
UNION 
SELECT STAFFID, FNAME ,deptid, birthdate FROM L_STAFF;

/*Queries from Union-All*/

SELECT STUDENTID, deptid FROM L_STUDENT
UNION ALL
SELECT ISSUENUM, deptid FROM L_ISSUEDETAILS;

SELECT STUDENTID,FNAME ,deptid, birthdate FROM L_STUDENT
UNION ALL
SELECT STAFFID, FNAME ,deptid, birthdate FROM L_STAFF;

/* QUERIES FOR INTERSECT */

SELECT deptid  FROM l_book
INTERSECT
SELECT deptid FROM l_issuedetails;

SELECT deptid ,issuenum FROM l_book
INTERSECT
SELECT deptid, issuenum  FROM l_issuedetails;


SELECT DEPTID,fname,lname FROM L_STUDENT
INTERSECT
SELECT DEPTID,fname,lname FROM L_STAFF;

/* Queries for 'MINUS' */

SELECT DEPTID, LNAME, FNAME FROM L_STUDENT
MINUS
SELECT DEPTID, LNAME , FNAME FROM L_STAFF;

SELECT DEPTID, LNAME, FNAME FROM L_STAFF
MINUS
SELECT DEPTID, LNAME , FNAME FROM L_STUDENT;

SELECT DEPTID , STAFFID FROM l_issuedetails
MINUS
SELECT DEPTID , STAFFID FROM L_STAFF;

SELECT DEPTID , STAFFID FROM l_staff
MINUS
SELECT DEPTID , STAFFID FROM l_issuedetails;

/* QERIES FOR JOINING THEM ALL*/

/**/


