/* CREATING A SIMPLE VIEW FOR L_STUDENT  */

CREATE VIEW MITAL_ST
(S_ID , S_LAST , S_FIRST , ADVISOR_ID , MAJOR_ID)
AS SELECT STUDENTID , LNAME , FNAME , STAFFID , DEPTID
   FROM L_STUDENT
   WHERE DEPTID = 'D102'
WITH CHECK OPTION;  

DESC mital_st;
SELECT * FROM mital_st;

/* CREATING A SIMPLE VIEW FOR L_STUDENT  */

CREATE VIEW MITAL_SF
(ADVISOR_ID, F_LAST , F_FIRST , MAJOR_ID)
AS SELECT STAFFID , LNAME , FNAME , DEPTID
  FROM L_STAFF
  WHERE DEPTID = 'D101'
WITH CHECK OPTION;
SELECT * FROM mital_sf;

/* CREATING A SIMPLE VIEW FOR L_AUTHOR  */

CREATE VIEW MITAL_AR
(A_ID , A_NAME , CONTACT_N0)
AS SELECT AUTHOR_ID , AUTHOR_NAME ,PHONE
   FROM L_AUTHOR
   WHERE AUTHOR_NAME = 'Shreya Agrwal'
WITH CHECK OPTION;   

/* 
SET LINESIZE 50;
DESC mital_ar;
SELECT * FROM mital_ar;

SET LINESIZE 100;
SELECT * FROM mital_ar;
*/



